#-----------------------------------------------------------------------
# OpenPOPCON Plotting Settings
#-----------------------------------------------------------------------

yax: "nG" # y-axis variable; nG for greenwald fraction, n20 for density
figsize: [8, 6] # figure size in inches

#----------------------
# Options per output
#----------------------

plotoptions: 
    Paux: 
        'plot': True # do not plot this output
        'color': 'r' # line color
        'linewidth': 3 # line width
        'label': r'$P_{aux}$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 10 # number of contour levels
    Pfusion: 
        'plot': True # do not plot this output
        'color': 'k' # line color
        'linewidth': 2 # line width
        'label': r'$P_{fus}$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 10 # number of contour levels
    Pohmic: 
        'plot': False # do not plot this output
        'color': 'k' # line color
        'linewidth': 2 # line width
        'label': r'$n_G$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 10 # number of contour levels
    Prad: 
        'plot': True # do not plot this output
        'color': 'purple' # line color
        'linewidth': 2 # line width
        'label': r'$P_{rad}$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 3 # number of contour levels
    Pheat: 
        'plot': False # do not plot this output
        'color': 'k' # line color
        'linewidth': 2 # line width
        'label': r'$n_G$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 10 # number of contour levels
    Ploss: 
        'plot': False # do not plot this output
        'color': 'k' # line color
        'linewidth': 2 # line width
        'label': r'$n_G$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 10 # number of contour levels
    Palpha: 
        'plot': False # do not plot this output
        'color': 'k' # line color
        'linewidth': 2 # line width
        'label': r'$n_G$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 10 # number of contour levels
    Pdd: 
        'plot': False # do not plot this output
        'color': 'k' # line color
        'linewidth': 2 # line width
        'label': r'$n_G$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 10 # number of contour levels
    Pdt: 
        'plot': False # do not plot this output
        'color': 'k' # line color
        'linewidth': 2 # line width
        'label': r'$n_G$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 10 # number of contour levels
    tauE: 
        'plot': False # do not plot this output
        'color': 'k' # line color
        'linewidth': 2 # line width
        'label': r'$n_G$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 10 # number of contour levels
    Q: 
        'plot': True # do not plot this output
        'color': 'orange' # line color
        'linewidth': 2 # line width
        'label': r'$Q$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.1f' # format for the on-contour labels
        'spacing': 'log' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        'min' : -1 # only used if scale is specified
        'max' : 2 # only used if scale is specified
        'levels': 4 # number of contour levels
    H89: 
        'plot': False # do not plot this output
        'color': 'k' # line color
        'linewidth': 2 # line width
        'label': r'$n_G$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 10 # number of contour levels
    H98: 
        'plot': True # do not plot this output
        'color': 'blue' # line color
        'linewidth': 2 # line width
        'label': r'$H_{98y2}$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.1f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 5 # number of contour levels
    vloop: 
        'plot': False # do not plot this output
        'color': 'k' # line color
        'linewidth': 2 # line width
        'label': r'$n_G$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 10 # number of contour levels
    betaN: 
        'plot': True # do not plot this output
        'color': 'forestgreen' # line color
        'linewidth': 2 # line width
        'label': r'$\beta_N$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 5 # number of contour levels
    n_G_frac: 
        'plot': False # do not plot this output
        'color': 'k' # line color
        'linewidth': 2 # line width
        'label': r'$n_G$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 10 # number of contour levels
    n20_max: 
        'plot': False # do not plot this output
        'color': 'k' # line color
        'linewidth': 2 # line width
        'label': r'$n_G$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 10 # number of contour levels
    n20_avg: 
        'plot': False # do not plot this output
        'color': 'k' # line color
        'linewidth': 2 # line width
        'label': r'$n_G$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 10 # number of contour levels
    T_i_max: 
        'plot': False # do not plot this output
        'color': 'k' # line color
        'linewidth': 2 # line width
        'label': r'$n_G$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 10 # number of contour levels
    T_i_avg: 
        'plot': False # do not plot this output
        'color': 'k' # line color
        'linewidth': 2 # line width
        'label': r'$n_G$' # label for the line
        'fontsize': 12 # font size for labels
        'fmt': '.2f' # format for the on-contour labels
        'spacing': 'lin' # lin or log spacing for the contour levels
        'scale': minmax # minmax or specified
        # 'min' : 0.0 # only used if scale is specified
        # 'max' : 1.0 # only used if scale is specified
        'levels': 10 # number of contour levels
    


